### ISSUE TITLE
The interface suddenly reported an error

### ISSUE THREAD

**Issue by xjpe** [fawmi/vue-google-maps#103]
GET https://maps.googleapis.com/maps/api/js?key=xxxxxxxxxxxxxxx&language=undefined&callback=vueGoogleMapsInit net::ERR_CONNECTION_CLOSED, 

Has the API of google maps changed?

**Comment by fawmi** [comment]
@xjpe 
Can you please create an example on stackblitz and demonstrate the error? 

Based on the error code you are seeing, I guess, it is a connection problem in your side.

**Comment by fawmi** [comment]
I will close this issue, feel free to open if you have updates.
