### ISSUE TITLE
How can I use this in Quasar? 

### ISSUE THREAD

**Issue by asdrubalp9** [fawmi/vue-google-maps#109]
I just installed this in a quasar bootfile, but I'm not sure if its done right.

```
import { boot } from 'quasar/wrappers'
import VueGoogleMaps from '@fawmi/vue-google-maps'
// "async" is optional;
// more info on params: https://v2.quasar.dev/quasar-cli/boot-files
const gmaps = VueGoogleMaps({
  load: {
    key: 'XXXX',
    language: 'es',
    libraries: 'places'
  }
})
export default boot(({ app }) => {
  app.component('VueGoogleMaps', gmaps)
})
```

and it gives the error: 

main.js:78 Uncaught (in promise) TypeError: Vue.mixin is not a function
    at install (main.js:78:7)

any help with this? please..

**Comment by Richard-Walter** [comment]
https://dev.to/quasar/how-to-use-google-maps-in-a-quasar-project-1c13

**Comment by asdrubalp9** [comment]
@Richard-Walter  thanks for the heads up!
