### ISSUE TITLE
Cluster icon moves with the map when panning

### ISSUE THREAD

**Issue by pokhrelashok** [fawmi/vue-google-maps#122]
When using marker cluster, when panning the map the cluster icon also pans along. 

**Expected behavior**
The cluster icon stays when the markers originally were.

**Screenshots**
The cluster icon where it should be
![image](https://user-images.githubusercontent.com/28856152/167282106-21e92ed3-5c41-473d-afe6-0e928338fb95.png)

On panning the map to a different location, the cluster icon pans along with the maps and moves.
![image](https://user-images.githubusercontent.com/28856152/167282114-99712a6a-8e95-497b-a554-c0519018eff1.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome
 - Version 101.0.4951.54

**Additional context**
Code
`
<GMapMap :options="options" :center="mapStore.currentPosition" :zoom="7" class="w-100 h-100">
    <GMapCluster :styles="mapClusterStyles">
      <GMapMarker
        v-for="(m, index) in markers"
        :key="index"
        :position="m.position"
        :clickable="true"
        :icon="'/images/map-marker.png'"
        @click="onMarkerClick(m)"
      >
        <GMapInfoWindow
          :closeclick="true"
          :opened="openedMarkerID === m.id"
          @closeclick="setOpenedMarker(null)"
        >
          <LocationInfo></LocationInfo>
        </GMapInfoWindow>
      </GMapMarker>
    </GMapCluster>
</GMapMap >
`
@fawmi/vue-google-maps version "^0.9.7",

**Comment by fawmi** [comment]
@pokhrelashok 
Can you elaborate the problem using a gif or a screen recording?  I can't follow exactly what problem you are having.

**Comment by pokhrelashok** [comment]
@fawmi here you go
https://www.loom.com/share/010cd6eb1de94990be93673cd2a0a60f

**Comment by emanday** [comment]
@pokhrelashok I had the same problem, my solution was to use width and height for cluster styles:

```
<GMapCluster :styles="myClusterStyles">
const myClusterStyles = [{ textColor: #000, url: 'my/url/icon.svg', width: 20, height: 20 }]
```

Then the cluster was not moving along with the map.

**Comment by pokhrelashok** [comment]
@emanday yup it works! Thank you so much.
