### ISSUE TITLE
Deprecated package dependency

### ISSUE THREAD

**Issue by felixranesberger** [fawmi/vue-google-maps#129]
**Describe the bug**
The extension currently throws a deprecated warning when installing. 

`npm WARN deprecated @googlemaps/markerclustererplus@1.2.10: It is recommended to use @googlemaps/markerclusterer instead of this package.`

**Comment by viktorkarbovskyi** [comment]
The same issue: https://github.com/fawmi/vue-google-maps/issues/115

**Comment by felixranesberger** [comment]
Closed due to duplication in #115
