### ISSUE TITLE
Map position not showing after fetch data from db and push to marker variable?

### ISSUE THREAD

**Issue by hengseyha** [fawmi/vue-google-maps#137]
**Are you asking a question?**
If you are asking a question, please use Github discussions for that. 

**Event xyz is not working?**
You should enable events, before using them https://vue-map.netlify.app/docs/#register-google-maps-events. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fawmi** [comment]
@hengseyha 
Can you please post a reproducible example on code sandbox ?

**Comment by hengseyha** [comment]
Now it is working, the issue is my mistake. thank you for your response.
