### ISSUE TITLE
Autocomplte doesn't work when it's inside dialog

### ISSUE THREAD

**Issue by Atidhaya** [fawmi/vue-google-maps#138]
Hello, thank you for making this wonderful repository! However, I've problem using Autocomplte within a dialog. 
The bug is, the dropdown doesn't work. Instead of showing dropdown of places to choose from, it shows nothing at all. And when I press enter on input, it couldn't find the location.

This happens regardless of having another autocomplete on the main component (page itself). At first I thought it has to related to ref problem but couldn't quite really figure out.

**To Reproduce**
1. Create Autocomplete inside a dialog
2. Type in on the search
3. See error (no visual dropdown)

**Expected behavior**
I expected the dropdown to occurs.

**Screenshots**
<img width="492" alt="Screen Shot 2565-07-18 at 09 18 57" src="https://user-images.githubusercontent.com/27059845/179436449-64234e2f-4f02-4a0e-bdb4-13138c2c06b1.png">
<img width="540" alt="Screen Shot 2565-07-18 at 08 33 03" src="https://user-images.githubusercontent.com/27059845/179436455-228fd8a5-065b-4974-870d-253846e928b4.png">
<img width="466" alt="Screen Shot 2565-07-18 at 08 33 55" src="https://user-images.githubusercontent.com/27059845/179436324-8b009bc3-bd57-4ce1-a41a-4ad3b34ff445.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 103.0.5060.114 (Official Build) (arm64)

NPM
- 16.15.1

I'm using Nuxt3

**Comment by fawmi** [comment]
Have you included places library? 
https://vue-map.netlify.app/components/autocomplete.html#load-google-maps-places

**Comment by Atidhaya** [comment]
> Have you included places library? https://vue-map.netlify.app/components/autocomplete.html#load-google-maps-places

Yes I did, the autocomplete is working fine outside of the dialog.

**Comment by fawmi** [comment]
Can you create a reproducible sandbox ?

**Comment by FirasGha** [comment]
same issue if autocomplete is called in a child component it's notworking, but it work in the parent component

**Comment by FirasGha** [comment]
actually after verification it works fine, the issue is when you use modal you have a z-index higher then the dropdown, the default google map dropdown index is 1000, 
to solve this just override the google map class z-index
.pac-container{
  z-index:9999999 !important;
}
