### ISSUE TITLE
google.maps.event.addDomListener() is deprecated in vue3

### ISSUE THREAD

**Issue by hengseyha** [fawmi/vue-google-maps#144]
**Are you asking a question?**
Could you please fix the deprecated message?

**Describe the bug**
google.maps.event.addDomListener() is deprecated, use the standard addEventListener() method instead: https://developer.mozilla.org/docs/Web/API/EventTarget/addEventListener

**Comment by zeddmaster** [comment]
The warning is related to the deprecated @googlemaps/markerclustererplus dependency
`"dependencies": {
    "@googlemaps/markerclustererplus": "^1.2.10"
  }`
You need to change the outdated package to @googlemaps/markerclusterer

**Comment by hengseyha** [comment]
Thank you.
