### ISSUE TITLE
Nuxt3:  fast-deep-equal does not provide an export named 'default'

### ISSUE THREAD

**Issue by Blemming** [fawmi/vue-google-maps#157]
## Describe the bug
Error in development in chrome
```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/fast-deep-equal/index.js?v=59f3ca57' does not provide an export named 'default'
```
Causes my whole script tag to pause in development.
But it transpiles and builds correctly in production environnement

## To Reproduce
1. Followed steps [here](https://github.com/fawmi/vue-google-maps/issues/95#issuecomment-1177544048)
2. And [here](https://github.com/fawmi/vue-google-maps/issues/150#issuecomment-1238108805)
3. Start project in development mode

## Expected behavior
The page to load and all subsequent vue script to load

### Desktop (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser Chrome
 - Version 106.0.5249.91

**Comment by websitevirtuoso** [comment]
I had the same issue had to fix via vite config. But I don't use nuxt
```

    optimizeDeps: {
      // fast-deep-equal doesnt have default export
      // https://github.com/vitejs/vite/issues/2679
      include: ['@apollo/client/core', '@apollo/client/cache', '@apollo/client/link/context', 'fast-deep-equal'],
      exclude: ['@apollo/react'],
    },
```

**Comment by Blemming** [comment]
> I had the same issue had to fix via vite config. But I don't use nuxt
> 
> ```
> 
>     optimizeDeps: {
>       // fast-deep-equal doesnt have default export
>       // https://github.com/vitejs/vite/issues/2679
>       include: ['@apollo/client/core', '@apollo/client/cache', '@apollo/client/link/context', 'fast-deep-equal'],
>       exclude: ['@apollo/react'],
>     },
> ```



This works for me ! thanks a lot

**Comment by PatrikBird** [comment]
Workaround: downgrade/pin version to 0.9.72 
https://github.com/fawmi/vue-google-maps/issues/164#issuecomment-1320840776

**Comment by ShwaibLeBon** [comment]
> optimizeDeps: {
>       // fast-deep-equal doesnt have default export
>       // https://github.com/vitejs/vite/issues/2679
>       include: ['@apollo/client/core', '@apollo/client/cache', '@apollo/client/link/context', 'fast-deep-equal'],
>       exclude: ['@apollo/react'],
>     },

Worked for me too
