### ISSUE TITLE
How do i get the place id from the autocomplete?

### ISSUE THREAD

**Issue by sebastienb** [fawmi/vue-google-maps#175]
Currently using the autocomplete to find locations but I need to also get the place ID. I see it in the network response when selecting a result in the autocomplete but I'm not sure how to get that data.

**Comment by Abhishek7Tech** [comment]
@sebastienb  Hi, Can you share the response please?

**Comment by sebastienb** [comment]
I was able to get it using the response. `this.$refs.input.$autocomplete.gm_accessors_.place.Kj.place.place_id;`
