### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/fast-deep-equal/index.js?v=21ec53d4' does not provide an export named 'default' (at index.esm.js?v=21ec53d4:1:8)

### ISSUE THREAD

**Issue by abdellatif-laghjaj** [fawmi/vue-google-maps#178]
Hello, i installed the lib via npm in my Vue js application, but I got this error
`Uncaught SyntaxError: The requested module '/node_modules/fast-deep-equal/index.js?v=21ec53d4' does not provide an export named 'default' (at index.esm.js?v=21ec53d4:1:8)`

Any solution!

**Comment by PatrikBird** [comment]
Hi, this issue exists a few times already. see https://github.com/fawmi/vue-google-maps/issues/164 for example.

**Comment by abdellatif-laghjaj** [comment]
Thanks for mentioning it bro
