### ISSUE TITLE
prop to change the icon of the marker

### ISSUE THREAD

**Issue by JavikusRod** [fawmi/vue-google-maps#18]
pass icon url or file
example

<GMapMarker
          :key="index"
          v-for="(m, index) in markers"
          :position="m.position"
          :clickable="true"
          :draggable="true"
          @click="center=m.position"
         :icon="https://developers.google.com/maps/documentation/javascript/examples/full/images/info-i_maps.png"
      />

**Comment by fawmi** [comment]
@JavikusRod You can pass a custom marker Icon to the GMapMarker component. 

So your example should work fine. 
```
 <GMapMarker
            :icon="'https://developers.google.com/maps/documentation/javascript/examples/full/images/info-i_maps.png'"
            :key="marker.id"
            :clickable="true"
            @click="openInfoWindow(marker.id)"
            v-for="marker in geoCoordinates"
            :position="marker.position"
        >

```
I have updated the docs here:
https://vue-map.netlify.app/components/marker.html#add-custom-icon

**Comment by fawmi** [comment]
@JavikusRod  Can you please confirm, that the solution work for you?

**Comment by fawmi** [comment]
I am closing this issue. feel free to open it again, if you have feedback on it.
