### ISSUE TITLE
I added (import VueGoogleMaps from "@fawmi/vue-google-maps") at the main.js file and the application breaks 

### ISSUE THREAD

**Issue by psalmistcom** [fawmi/vue-google-maps#198]
The requested module '/node_modules/fast-deep-equal/index.js?v=848aeb3e' does not provide an export named 'default'

**Comment by will-lucena** [comment]
+1

node version: 18.17.1

**Comment by will-lucena** [comment]
@psalmistcom I've searched in the other issues and found @tahaipek's solution in #148 and it worked for me:

add it in your vite.config.js
```
 optimizeDeps: {
    include: [
      "@fawmi/vue-google-maps",
      "fast-deep-equal",
    ],
  },
```

**Comment by psalmistcom** [comment]
@will-lucena thanks for your response. I've actually done this and still not work. 

I have to downgrade my Vue app and the package. Then delete the node_modules and reinstall it before it works.
