### ISSUE TITLE
google.maps is not defined

### ISSUE THREAD

**Issue by toshkoevo** [fawmi/vue-google-maps#20]
**Describe the bug**
The sample code to add a button to the map at https://vue-map.netlify.app/components/map.html references a constant from google.maps.ControlPosition, however the whole google object is undefined.

How do we access this object.

**Comment by fawmi** [comment]
@toshkoevo  
Thanks for the issue. I have updated the documentation with a complete example. 
Do let me know, if you still have problem with adding custom buttons.

**Comment by fawmi** [comment]
I am closing this issue. If you still have problem, reopen the issue.

**Comment by catherineluse** [comment]
I had the same issue when trying to do something like
```
const bounds = new google.maps.LatLngBounds()
```
I get `Map.vue?d012:31 Uncaught (in promise) ReferenceError: google is not defined`.

https://github.com/catherineluse/gennit-vue/blob/map/src/components/event/Map.vue#L10
