### ISSUE TITLE
Event doesn't work

### ISSUE THREAD

**Issue by domadev812** [fawmi/vue-google-maps#22]
**Describe the bug**
The events are not working except client event.

**To Reproduce**
1. Add dragend into Marker something like
`<GMapMarker @dragend="getMarkerLocation" />`

**Expected behavior**
getMarkerLocation function should be triggered if I drag the map pin

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac OS 10.14
 - Browser Chrome
 - Version 89.0

**Smartphone (please complete the following information):**

**Additional context**
I check the code in node_modules and I don't think you add the lister for the events except click.
This is original code in your library.
```
inst.addListener('click', ()=> {
          this.$emit('click')
        });
```
And I update the manually to fix the issue.
```
inst.addListener('click', ()=> {
  this.$emit('click')
});
inst.addListener('dragend', (event)=> {
  this.$emit('dragend', event)
});
```
After I update, the function is triggered.

I'd like you to check and update the modules and it would be helpful.

Or if I did wrong, I'd like you to let me know the way to trigger the events without updating library.

Thanks

**Comment by fawmi** [comment]
Can you please create a reproducable example? 
Here is a basic example on stackblitz to put your example on. 
https://stackblitz.com/edit/vue-google-maps-marker-axmbmu?file=src%2Fcomponents%2FComponentWithMap.vue

**Comment by domadev812** [comment]
As I mentioned, the dragend event is not working.
I update the example on stackblitz

**Comment by dlinc** [comment]
@fawmi and @domadev812 , using the stackbliz example I noticed the same thing -- but when I wrapped in ```GMapCluster``` the events do fire.

Maybe running ```@click``` on a Marker without the ```GMapcluster``` wrapper needs another look? It would be better to not cluster, in my case too, if that is do-able... :)-

**Comment by fawmi** [comment]
@dlinc thanks for the Info, I will look at it the next days.

**Comment by domadev812** [comment]
@fawmi  @dlinc 
Actually click event is triggered, but another events such as dragend, dragstart, etc are not triggered.

**Comment by fawmi** [comment]
@domadev812 this should be fixed in the latest release. Can you please update and check, whether the fix is working for you?

**Comment by fawmi** [comment]
@dlinc  thanks for the tip. I can confirm, that it is related to the GMapCluster. I will release a new version with fix tomorrow.

**Comment by fawmi** [comment]
@dlinc  @domadev812 This problem should be solved in the latest release. 
Please let me know, if you still have problem with events.

**Comment by fawmi** [comment]
I close this issue. If you continue to have problems feel free to open it again

**Comment by fawmi** [comment]
I close this issue. If you continue to have problems, feel free to open it again

**Comment by Mounir-Bennacer** [comment]
Hi Fawmi, 
i'm experiencing the same issue


OS: mac OS 11.0.1
Browser Chrome
Version 90.0.4430.212 (Official Build) (x86_64)

```js
<template>
  <div>
    <GMapMap
        style="width: 50vw; height: 400px"
        map-type-id="terrain"
        :center="center"
        :zoom="zoom"
        :options="{
                      zoomControl: true,
                      mapTypeControl: false,
                      scaleControl: true,
                      streetViewControl: false,
                      rotateControl: false,
                      fullscreenControl: true,
                }"
    >
      <GMapCluster :zoomOnClick="true">
        <GMapCircle
            v-for="(pin, index) in markers"
            :key="index"
            :center="pin.position"
            :radius="100"
            :draggable="true"
            :options="circleOptions"
            @dragend="getCircleLocation"
        ></GmapCircle>
      </GMapCluster>
    </GMapMap>
  </div>
</template>

<script>
import axios from "axios";

export default {
  name: 'Map',
  data() {
    return {
      user_id: document.querySelector("meta[name='user_id']").getAttribute('content'),
      business_id: document.querySelector("meta[name='business_id']").getAttribute('content'),

      // Marker options
      zoom: 15,
      center: {},
      markers: [],

      // Circle options
      circleOptions: {
        strokeColor: "#FF0000",
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: "#FF0000",
        fillOpacity: 0.35,
      },
    }
  },

  methods: {
    getCircleLocation(event) {
      console.log(event)
    },

    getCircleOption(event) {
      console.log(event)
    },

    getEmployeeLocation: function () {
      axios.get(someurl)
          .then((response) => {
            this.markers.push(response.data)
          }).catch(err => {
        console.error(err)
      })
    },

    getBusinessLocation: function () {
      axios.get(someurl)
          .then((response) => {
            this.markers.push(response.data)
          }).catch(err => {
        console.error(err)
      })
    },

    getCenter: function () {
      axios.get(someurl)
          .then((response) => {
            this.center = response.data
          }).catch(err => {
        console.error(err)
      })
    }
  },

  mounted() {
    this.getCenter()
    this.getEmployeeLocation()
    this.getBusinessLocation()
  }
}
</script>
```


Thanks

**Comment by fawmi** [comment]
@Mounir-Bennacer 
are you using the latest version?

**Comment by XaviTorello** [comment]
This should be reopened, I can confirm that is not working in `"@fawmi/vue-google-maps": "^0.9.3"` (with `"vue": "^3.0.2"`)
 
This does not emits nothing for `drag`, `dragstart` or `dragend` (with or without a `GMapCluster` child). But it emits correctly the `zoom_changed`:
```
    <GMapMap
      ...
      @zoom_changed="(...e) => emit('zoom_changed', ...e)"
      @dragstart="(...e) => emit('dragstart', ...e)"
      @drag="(...e) => emit('drag', ...e)"
     />
```

Setting the listener manually works:
```
        mapRef.$mapPromise.then((map) => {
          google.maps.event.addListener(map, "drag", (...e) => {
            emit("drag", ...e);
          });
```

Could this be reviewed? Many thanks!
