### ISSUE TITLE
Missing autocomplete component error

### ISSUE THREAD

**Issue by AnoRebel** [fawmi/vue-google-maps#23]
**Describe the bug**
I was using v0.7.11, but decided to update the latest v0.7.16, but i get an src/components/autocomplete.vue 404 error in the console and the page isn't loading.

**To Reproduce**
1. Install the v0.7.16
2. Create a simple map example
3. Run example, check Dev console

**Expected behavior**
Expected page to load normally

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser: Brave Browser
 - Version: Latest(v1.23.75)

**Comment by fawmi** [comment]
@AnoRebel This problem is solved in the latest release. 
Please check whether you still have problem. If not, you can close the issue.

**Comment by AnoRebel** [comment]
Thanks, it works now.. Great work!!
