### ISSUE TITLE
[Question] How to draw polylines

### ISSUE THREAD

**Issue by AnoRebel** [fawmi/vue-google-maps#25]
I can see a `polyline.js` file in the components directory but no documentation on it and I would really like to use it.
So, I was asking on how I may be able to implement it in my app.
Thanks in advance.

**Comment by fawmi** [comment]
@AnoRebel 
I added documentation for the `GMapPolyline` component: 
https://vue-map.netlify.app/components/polyline.html

Please let me know if you have some problem with it. if it works, you can close this issue.

**Comment by AnoRebel** [comment]
Great! Worked perfectly. Thanks for the quick reply.
No issues at all, but would be glad if you could add a list of the options that can be passed in the options prop.
Again, great work!

**Comment by ecaballerocds** [comment]
Where can a I get a list of the posible options?
