### ISSUE TITLE
Add documentation addition - adding libraries

### ISSUE THREAD

**Issue by Kyle123** [fawmi/vue-google-maps#28]
Thanks for the library, it's really useful. In the docs, there is the autocomplete component, however to use this, you must add the `places` library when registering with vue. This is missing from the documentation, would be worth adding this - I'd have done it, but couldn't find the repo for the docs:

To use the AutoComplete component, you must add the places API in the google console and add the library to the libraries array when registering with vue:

```
const app = createApp(App);
app.use(VueGoogleMaps, {
    load: {
        key: 'YOUR_API_KEY_COMES_HERE',
        libraries: ['places']
    },
}).mount('#app')
```

**Comment by fawmi** [comment]
@Kyle123 
Thanks for the feedback. 

The docs are hosted in a separate Repository
https://github.com/fawmi/vue-google-maps-docs

To use some component, they should either be defined as you explained or imported all at once. 
I will document this behavior, but you can open a PR in the Docs repository as well.

**Comment by vBoykoGit** [comment]
How can I get place from coordinates of my marker?

**Comment by fawmi** [comment]
@vBoykoGit 
Can you please open a separate Issue for that?  This issue is about adding individual libraries.
