### ISSUE TITLE
Maps not loading online

### ISSUE THREAD

**Issue by MachariaK** [fawmi/vue-google-maps#30]
My map is working on localhost but not online. I have removed keys restrictions but still doesn't load the map online with no errors in the console.

**Comment by fawmi** [comment]
@MachariaK 
This should have something to do with your network. 

Can you show me the network tab of Chrome Devtools?
Is your app accessible somewhere? so that I have a look at it myself?

**Comment by MachariaK** [comment]
Hello. I have sent the link and login credentials via Twitter. I couldn't find a way to send the details privately on here. Thank you in advance.

**Comment by fawmi** [comment]
@MachariaK 

Looking at your Dashboard, maps are properly loaded in your Dashboard. 

You forgot to pass the style attribute to the GMapMap component

```

<GMapMap
      :center="center"
      :zoom="7"
      map-type-id="terrain"
      style="height: 100%; width: 100%;"
  > </GMapMap>
```
  
Or alternatively you should define `.vue-map` styles in CSS.

**Comment by MachariaK** [comment]
I had passed the style attribute and I don't know why it was not working. As you have advised, I have added the `.vue-map` style and the map can now show both online and on localhost. Thanks.
