### ISSUE TITLE
It's not work on main.ts

### ISSUE THREAD

**Issue by YN00** [fawmi/vue-google-maps#31]
I import VueGoogleMaps on main.ts but it showed me type error.

TS2345: Argument of type 'typeof import("C:/mydirectory/@fawmi/vue-google-maps/types/index")' is not assignable to parameter of type 'Plugin_2'.   Property 'install' is missing in type 'typeof import("C:/mydirectory/@fawmi/vue-google-maps/types/index")' but required in type '{ install: PluginInstallFunction; }'

I saw this issue.
How can i solved it?

**Comment by fawmi** [comment]
@YN00 
Main.ts does not exist in the component, you should import main.js

Typescript support is planned and in work, but not final. That is why you should work with Javascript version.
