### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by asdfmovie334** [fawmi/vue-google-maps#33]
Hello, does  your component provide search box input for the map?
Also, how can I add custom points on the map, for e.g whenever I click on the map, I want to add circle there and push the `lat` and `lng` to an array. Is there click listener that gets the lat and lng?

**Comment by fawmi** [comment]
Well as search box, you can use autocomplete component. 
You can register click event on the GMapMap component and read the lat and long from the event details. Then you can push the lat and long to the list of markers if you want.

**Comment by fawmi** [comment]
@asdfmovie334 

I close this ticket. You can reopen it if you still have questions.
