### ISSUE TITLE
On dragend event is undefined

### ISSUE THREAD

**Issue by Sephen** [fawmi/vue-google-maps#35]
**Describe the bug**
The on-dragend event is fired but the passed event is undefined

**To Reproduce**
```
<GMapMap ref="myMapRef" :center="center" :zoom="14" map-type-id="roadmap" class="map" :options="{
    zoomControl: false,
    mapTypeControl: false,
    scaleControl: false,
    streetViewControl: false,
    rotateControl: false,
    fullscreenControl: false,
  }"
  >

  <GMapMarker
    :draggable="true"
    :clickable="true"
    :position="marker.position"
    @dragend="debug"
    icon="/markers/icon.png"
    />
</GMapMap>
```
	
Method
```
debug (event) {
	console.log(event)
}
```

Console log
undefined

**Expected behavior**
Return event on dragend

**Desktop (please complete the following information):**
 - OS: Mac 11.2.3
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by fawmi** [comment]
This bug is fixed on the latest release. 

Make sure, you update to the latest version (0.8.7)
