### ISSUE TITLE
Add Method get Coordinate when click map

### ISSUE THREAD

**Issue by curlylazy** [fawmi/vue-google-maps#37]
hey please add method how to get coordinates when we click on the map.

**Comment by fawmi** [comment]
Well, you can access the google maps object and register click event on it.

Check out an example here:
https://stackblitz.com/edit/vue-google-maps-marker-v4uz7b?file=src/components/ComponentWithMap.vue

**Comment by curlylazy** [comment]
woah great thank you, i am new in vue, your lib help me so much,
again thank you so much @fawmi
