### ISSUE TITLE
[Help] Open window info on click example needed

### ISSUE THREAD

**Issue by blackjak231** [fawmi/vue-google-maps#38]
Hello !

I've been at it for hours and my brain is going to melt. Would it be possible to get an example on how to open/close info window based on the click on the marker ? 

I tried setting the opened attribute to true/false through `$refs.markerRef.$infoWindowObject.opened` but the method `openInfoWindow` is not triggered.

I cannot add a value to the marker's data though, which seemed to be the obvious solution.

Thanks for any help :)

**Comment by fawmi** [comment]
Well, it is quite simple. 
You can simply modify the `:opened` prop using click event on the marker. 

I updated docs and added an example here: 
https://vue-map.netlify.app/components/info-window.html#open-close-info-window-on-marker-click

**Comment by blackjak231** [comment]
Amazing :) I must have been tired to not think about this... 

Thanks as well for the clear example !
