### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by nathanaelphilip** [fawmi/vue-google-maps#40]
**Is your feature request related to a problem? Please describe.**
It’d be nice to be able to pass an icon object instead of just a url. That way we can size the icon for each marker.

**Describe the solution you'd like**
Expand the `icon` prop to handle and object or a string.

**Comment by fawmi** [comment]
This is already possible,  i updated the docs with an example.

https://vue-map.netlify.app/components/marker.html#add-custom-icon

**Comment by nathanaelphilip** [comment]
@fawmi thank you! :) thanks for putting this plugin together – it’s very well thought out.

**Comment by mstnorris** [comment]
@fawmi is it possible to use another Vue component as the icon, e.g. using the FontAwesome Vue package?
