### ISSUE TITLE
Build for Production fails to display Map

### ISSUE THREAD

**Issue by markbarton** [fawmi/vue-google-maps#42]
**Describe the bug**
Everything works fine using a standard npm run serve but as soon as I do a npm run build the Map fails to load.
I have hardcoded the API key in the main.js so its not pulling from an env file.

I added a development build script to the package.json = "buildDev": "vue-cli-service build --mode development" and tested the new app.js file it created and it worked.  No CSS was changed so it can only be the Vue CLI build for production which is stopping the map displaying.

So to confirm the Vue is running ok as its pulling data from an API to display a list down the side of the map - its just the Google Map itself which will not display.

Just wondered if you had come across this before.

Thanks

**Comment by fawmi** [comment]
@markbarton 
Can you please post a link to a repo where I can reproduce the bug? I can unfortunately not reproduce this bug.

**Comment by fawmi** [comment]
I will close this issue due to no response. Feel free to reopen it, if you still have problems.
