### ISSUE TITLE
TypeScript support, and the composition API

### ISSUE THREAD

**Issue by obadakhalili** [fawmi/vue-google-maps#43]
I really would like to use this component library, but the lack of TypeScript support is utterly annoying. The `types/index.d.ts` literally has types for an addition function! 😅. Add to that the fact that you're using Vue 3 as if it's Vue 2, you should consider using the composition API.

Thanks for the effort you put in, anyway,

**Comment by fawmi** [comment]
A typescript issue already exists, and typescript support is already WIP. 
Using composition API in Vue 3 is an option, but not a must.
