### ISSUE TITLE
Vite produces error on import - marker-clusterer-plus does not provide an export named 'default'

### ISSUE THREAD

**Issue by adarshmadrecha** [fawmi/vue-google-maps#45]
**Describe the bug**
When using vite, the vite throws below error
```
The requested module '/node_modules/marker-clusterer-plus/src/markerclusterer.js?v=9cd0e59f' does not provide an export named 'default'
```

**To Reproduce**
1. Instantiate Vue project using `vite`
2. Import library in `main.js`
`import VueGoogleMaps from '@fawmi/vue-google-maps'`

**Expected behavior**
No error

**Screenshots**

![image](https://user-images.githubusercontent.com/11911938/128066243-0264cc6c-66e9-433e-89bd-ddb0c46435ee.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 92

**Additional context**
Should we move to using https://github.com/googlemaps/js-markerclustererplus instead of no longer maintained https://github.com/mikesaidani/marker-clusterer-plus

**Comment by adarshmadrecha** [comment]
Found a workaround this, in case anyone comes looking here 

```js
  // in vite.config.js
  optimizeDeps: {
    include: [
      'marker-clusterer-plus'
    ]
  }
```

Moving to https://github.com/googlemaps/js-markerclustererplus instead of no longer maintained https://github.com/mikesaidani/marker-clusterer-plus will also solve this error, as `@google/markerclustererplus` exports are not erroneous.

**Comment by joepagan** [comment]
I also had to add `vue-google-maps` to optimizeDeps because I was getting:

```
Uncaught SyntaxError: The requested module '/node_modules/@fawmi/vue-google-maps/src/utils/lazyValue.js' does not provide an export named 'default'    main.js:1
```

```js
optimizeDeps: {
    include: [
      '@fawmi/vue-google-maps',
      'marker-clusterer-plus',
    ],
  },
```

**Comment by fawmi** [comment]
@adarshmadrecha 
This should be fixed in the recent version, can you please check whether this exists in version 0.9.3?

**Comment by adarshmadrecha** [comment]
@fawmi ❤️ ,   Thanks for the fix. I tested on `v0.9.4` There is no longer need to add vite config.

I think, this https://github.com/fawmi/vue-google-maps/commit/303281d85ae1e453faa9566c7b95e7b7ed7dd13d commit did the trick.

**Comment by rouralberto** [comment]
Using the latest Vue, Vite and this library, I faced today this with the same issue with `fast-deep-equal`. I added it to the `optimizeDeps` and it worked fine:

```node
  optimizeDeps: {
    include: [
      'fast-deep-equal',
    ],
  },
```
