### ISSUE TITLE
Custom Map style is not working

### ISSUE THREAD

**Issue by afrazahmmad** [fawmi/vue-google-maps#46]
Hi dear!
Thanks for creating for great plugin.
I want to use silver theme of map.
So I have used the suggested official site to create map styles.
https://mapstyle.withgoogle.com/

But when I apply it on GMapMap component, it doesn't take effect.

     <GMapMap 
                :zoom="15"
                :center="latlong"
                map-type-id="terrain"
                style="height: 200px"
                :style="gMapStyle"
            >
                <GMapMarker
                    :key="some.id"
                    :position="latlong"
                ></GMapMarker>
            </GMapMap>

But result is same as show below
![image](https://user-images.githubusercontent.com/22490945/128305858-7187d8cc-b776-47e7-90f6-36d2cb741ede.png)

**Comment by fawmi** [comment]
@afrazahmmad 
Can you please post a reproducible example on Stackblitz?

**Comment by fawmi** [comment]
I updated docs with an example and external link to Stackblitz. 
https://vue-map.netlify.app/components/map.html#provide-your-own-style

**Comment by afrazahmmad** [comment]
@fawmi Thanks a lot dear.
https://vue-map.netlify.app/components/map.html#provide-your-own-style solved the issue.
