### ISSUE TITLE
Question: how to reduce init JS filesize when using vue-google-maps

### ISSUE THREAD

**Issue by flipvh** [fawmi/vue-google-maps#48]
hi There. For many sites, the google maps JS is not necessary to have on the init file load. But with app.use this is what happens.

With Vue 3 I do not see an easy way to load this library after app mounting, in a specific (asynced) component. Or am I missing something?

Thanks in advance!

**Comment by fawmi** [comment]
@flipvh 
What you are asking is a webpack related question. It has nothing to do with this library or vue at all. 
Search for "Code splitting in webpack" and you will find how to split your code. 

Newest versions of webpack and Vue Cli supports  dynamic imports  out of box.
