### ISSUE TITLE
GMapInfoWindow does not reopen

### ISSUE THREAD

**Issue by restlesskos** [fawmi/vue-google-maps#50]
GMapInfoWindow does not reopen if you close the window and click on the marker again. Tell me how to fix it.

**Comment by agatheflorentin** [comment]
Someone already opened an issue : #44

**Comment by fawmi** [comment]
In order for map events to be forwarded, they should be enabled first. 
For example, if you want to forward `closeclick`, you should add the props `closeclick="true"` to the component.  and the register `@closeclick="closemyInfowindow"`

[Here is an example with Google maps InfoWindow, which can be opened and closed and reopened. ](https://codesandbox.io/s/vue-3-google-maps-forked-ohplq?file=/src/components/Map.vue:342-401)


Please reopen the issue, if the suggested solution does not work for you.
