### ISSUE TITLE
Error when including Marker

### ISSUE THREAD

**Issue by francisjavier** [fawmi/vue-google-maps#54]
I get this error but only when I add the GMapCluster/GMapMarker inside the GMapMap:

mapElementMixin.js:26 Uncaught TypeError: this.$mapPromise.then is not a function
    at Proxy.provide (mapElementMixin.js:26)
    at applyOptions (VM5793 runtime-core.esm-bundler.js:5502)
   
The code I'm using is currently identical (to the best of my knowledge) to what is used in the codesandbox example, including the 0.8.7 version. Can someone point me in the direction to resolve this issue?

Thanks.

**Comment by fawmi** [comment]
@francisjavier 
It is difficult to say, why are you getting the error. Is it possible to create a reproducible sandbox?

**Comment by francisjavier** [comment]
@fawmi Thank you for the quick response, in the process of reproducing by clearing out all of the node_modules and compiled javascript files, it got fixed. My guess is there was some dependency causing the problem.

**Comment by fawmi** [comment]
OK, great that your problem is solved.

**Comment by Wtk0930** [comment]
> @fawmi Thank you for the quick response, in the process of reproducing by clearing out all of the node_modules and compiled javascript files, it got fixed. My guess is there was some dependency causing the problem.

I am sorry， How do you solve it...
