### ISSUE TITLE
How to access google api?

### ISSUE THREAD

**Issue by gottenwit** [fawmi/vue-google-maps#69]
### My project
**main.js**
```
import VueGoogleMaps from '@fawmi/vue-google-maps'

createApp(App)
  .use(VueGoogleMaps, {
    load: {
      key: 'YOUR_API_KEY'
    }
  })
  .mount('#app')
```

**Page1.vue**

Example : 
`var myLatlng = new google.maps.LatLng(center.lat, center.lng)`

### My problems
I want to access object api. Loss import something?

### From Heatmap doc
```
<template>
  <GMapMap
    ref="myMapRef"
    :center="center"
    :zoom="zoom"
    style="width: 100%; height: 600px"
  >
    <GMapHeatmap :data="heatData"></GMapHeatmap>
  </GMapMap>
</template>
<script>
export default {
  name: 'App',
  setup() {
    const center = {lat: 52.2985593, lng: 104.2455337}
    const zoom = 12
    const myMapRef = ref();
    const heatData = ref([])

    watch(myMapRef, googleMap => {
      if (googleMap) {
        googleMap.$mapPromise.then(map=> {
          heatData.value = [
            {location: new google.maps.LatLng({lat: 52.2985593, lng: 104.2455337})},
          ];
        })
      }
    });

    return {
      center,
      zoom,
      heatData,
      myMapRef
    }
  },
}
</script>

```

**Then**
![image](https://user-images.githubusercontent.com/52517915/136765930-1489672b-21f8-41ba-99cb-5daa6e37eca5.png)

**Comment by catherineluse** [comment]
You just need to install the Google map types separately. Then it will work.

```
npm i -D @types/google.maps
```

Docs: https://developers.google.com/maps/documentation/javascript/using-typescript

**Comment by gottenwit** [comment]
> You just need to install the Google map types separately. Then it will work.
> 
> ```
> npm i -D @types/google.maps
> ```
> 
> Docs: https://developers.google.com/maps/documentation/javascript/using-typescript

Thank you so much.

I installed @types/google.maps then no problems. But I stucked with cycle many hour.
I can use this types directly.
Then
![image](https://user-images.githubusercontent.com/52517915/137303881-452c42d5-5bfb-4413-8fb0-2455cfe7f387.png)

And I type to fixed on top.
`/*global google*/`

**Comment by CHOMNANP** [comment]
Just curios how do you manage to use google api @gottenwit.

I managed to install the `npm i -D @types/google.maps`, yet I'm not sure how to import the google object.
