### ISSUE TITLE
Can the plugin set the language

### ISSUE THREAD

**Issue by xjpe** [fawmi/vue-google-maps#80]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fawmi** [comment]
Yes this is possible to define a language other than user's preferred browser language. 

https://vue-map.netlify.app/docs/#basic-usage


Here is an example: 
https://stackblitz.com/edit/vue-google-maps-marker-kpzjbh?file=src%2Fmain.js
