### ISSUE TITLE
in GMapMarker I can't set icon using a variable

### ISSUE THREAD

**Issue by this1-it** [fawmi/vue-google-maps#97]
this is working

```
 <GMapMarker
            :icon="'assets/icon/favicon.png'"
            :key="marker.id"
            v-for="marker in markers"
            :position="marker.position"
        >
```

I want to show a different local custom icon for each marker but I got only default marker from google

```
        <GMapMarker
          v-for="m in markers"
          :key="m.id"
          :icon="m.icon"
          :position="m.position"
          :clickable="true"
          :draggable="false"
          @click="center = m.position"
        >
```

I'm assigning like this, is it right ?

`marker.icon = 'assets/icon/favicon.png';
`

**Comment by fawmi** [comment]
@this1-it 
Try using absolute paths (your-domain.com/assets/icon/favicon.png) 
Or import the icon 
```
import myIcon from './assets/icon/favicon.png'


and in your template :icon="myIcon"
```

**Comment by this1-it** [comment]
Hi fawmi,
thank you for answering but it did not worked

In my template, I need to assign icon using a variable in v-for
I assign m.icon and m.description but I cannot these values

It seems that id, name, position are the only attributes allowed
Have you any clue ?

`        <GMapMarker
          v-for="m in markers"
          :key="m.id"
          :icon="m.icon"
          :position="m.position"
          :clickable="true"
          :draggable="false"
        >
          <GMapInfoWindow>
            <div>
              {{m.name}}<br />
              {{m.description}}
            </div>
          </GMapInfoWindow>
        </GMapMarker> `

I would like to understand why is needed to assign with double quotes and single quotes ?

` :icon="'assets/icon/favicon.png'"`
